### ISSUE TITLE
[bug] links in feed's footer opens xml stuff instead of html

### ISSUE THREAD

**Issue by pro465** [rust-lang/blog.rust-lang.org#1009]
in #1008, @rylev seemed to think the links are as expected. so, if they are right, something is wrong in the generator that makes it skip the `{{root}}[/inside-rust]/feed.xml` links, not replacing them with `../index.html` links

**Comment by faptc** [comment]
You shall read more about what RSS is: https://en.m.wikipedia.org/wiki/RSS#:~:text=RSS%20(RDF%20Site%20Summary%20or,standardized%2C%20computer-readable%20format.
