### ISSUE TITLE
May 15 is the 8th anniversary birthday of Rust, do we have a celebration blog post?

### ISSUE THREAD

**Issue by Folyd** [rust-lang/blog.rust-lang.org#1104]
We forgot the 7th anniversary birthday of Rust, I hope we have one this year.
![image](https://github.com/rust-lang/blog.rust-lang.org/assets/3369694/1222e4dc-e834-4758-aaeb-09c360729825)

**Comment by rylev** [comment]
I don't think we have anything in the pipeline for this unfortunately, and I'm not sure we'll have time to create one. As with people birthdays, the older you get, arguably the less special it becomes :cry:. Perhaps we'll do better next year, and I definitely think we'll want to have one for the 10th anniversary!

**Comment by CleanCut** [comment]
_Rust says..._

> No gifts this year, please! I just want my family to gather around and build reliable and efficient software together.
