### ISSUE TITLE
Rust Survey 2022: Graphs are counts, not proportions

### ISSUE THREAD

**Issue by jtkiley** [rust-lang/blog.rust-lang.org#1128]
In the [Rust Survey 2022 post](https://blog.rust-lang.org/2023/08/07/Rust-Survey-2023-Results.html), the graph results are reported as counts, even though substantially all of the characterizations are proportions/percentages (which I think is a better comparison here).

This is more of an issue where there are two years in a bargroup, because the underlying data has different numbers of responses, so the shape of the graph will be different (even if not dramatically so given the closeness in counts).

Also, the "Rust Usage at Work" graph leaves out a now-excluded option, which makes the graph hard to interpret, and it makes the characterization about a "51.8% increase compared to the previous year" perhaps too strong for the evidence. The change in that bar is both from real change over time and from an additional option that would have drawn some of the responses had it been offered. It's still quite encouraging that removing an overlapping middle option (my interpretation anyway) had a number of respondents land in the "Yes, majority" group. As a hot take, I think removing a non-mutually-exclusive option like that is probably the right call, but you should include it on the graph (and switch to proportions).

Thanks for doing and reporting these surveys. It's really interesting to see both current responses and change over time.

**Comment by Kobzol** [comment]
Thank you for the report. There were definitely things that could be improved in the 2022 survey, there was a lack of time and people to work on the result analysis this year. Next year, we will try to do a better job.

**Comment by Kobzol** [comment]
https://github.com/rust-lang/blog.rust-lang.org/pull/1249 should improve upon this a lot.
