### ISSUE TITLE
Release Team link is broken

### ISSUE THREAD

**Issue by alexhrao** [rust-lang/blog.rust-lang.org#1246]
The release team link (as seen on [this page](https://blog.rust-lang.org/inside-rust/2024/02/04/1.76.0-prerelease.html)) no longer works. The link is `https://www.rust-lang.org/governance/teams/release`

I can't seem to find where it _should_ point to, but in any case right now it's a broken link.

**Comment by ehuss** [comment]
Thanks for the report! There is an issue with the website where the redirects have stopped working. This is tracked in https://github.com/rust-lang/www.rust-lang.org/issues/1921.

**Comment by CleanCut** [comment]
Perhaps the release team is part of (or was folded into?) the [Infra Team](https://www.rust-lang.org/governance/teams/infra)?

Releases is listed as their responsibility:



![Image](https://github.com/rust-lang/blog.rust-lang.org/assets/5838512/6f7276b8-f209-415c-82d9-a52f3f397efb)

**Comment by CleanCut** [comment]
@ehuss There isn't a redirect listed for `governance/teams/release` in that file on the commit you linked or on `master`.

**Comment by senekor** [comment]
The route `/governance/<section>/<team>` is rendered dynamically based on data from https://team-api.infra.rust-lang.org/v1/teams.json. There actually is a release team in that data (a subteam of infra), so I think this is an issue on the side of www.rust-lang.org. (But it is a separate issue from the general redirect problem.) I'll investigate further.

**Comment by senekor** [comment]
Looks like pages for subteams are deliberately not shown. Since release is a subteam of infra, that applies there as well. I don't know what the reason or the best way to fix it is. The code snippet is from [here](https://github.com/rust-lang/www.rust-lang.org/blob/660f75c3b47fb4ceeb90008be42cfb9073b08517/src/teams.rs#L100).

```rust
// Don't show pages for subteams
if let Some(subteam) = &main_team.subteam_of {
    // Launching-pad does not have a page of its own, but we do want
    // to show the working groups that are inside it.
    if subteam != "launching-pad" {
        return Err(TeamNotFound.into());
    }
}
```

**Comment by senekor** [comment]
Ok it makes sense to me now, the subteams are listed as sections on the page of the parent team. So the correct link would probably be https://www.rust-lang.org/governance/teams/infra#Release%20team.
