### ISSUE TITLE
`incompatible_msrv` does not seem to be launched in 1.77

### ISSUE THREAD

**Issue by robertbastian** [rust-lang/blog.rust-lang.org#1277]
### Description

It triggers an unknown lint warning.

See [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7af97064611efc571b065fe5d2caa8a6) playground, clippy-stable (1.77) doesn't know the lint, beta (1.78-beta-1) does though.

**Comment by Manishearth** [comment]
https://blog.rust-lang.org/2024/03/21/Rust-1.77.0.html#clippy-adds-a-new-incompatible_msrv-lint this section should be removed and reused for the 1.78 release 

cc @Mark-Simulacrum and @rust-lang/release

**Comment by Mark-Simulacrum** [comment]
I'm happy to merge a PR dropping it, won't have a chance to put that together for some time.

**Comment by weihanglo** [comment]
So it was the lint didn't make it into the release train I guess?

https://github.com/rust-lang/rust-clippy/blob/443f459f98841001b2c2041adda05b9318f44b24/clippy_lints/src/incompatible_msrv.rs#L36-L37
