### ISSUE TITLE
Footnote links aren’t made into hyperlinks

### ISSUE THREAD

**Issue by linkmauve** [rust-lang/blog.rust-lang.org#1301]
At https://blog.rust-lang.org/2024/03/30/i128-layout-update.html the links in the footnotes aren’t converted to hyperlinks, making them more cumbersome to follow.

**Comment by ehuss** [comment]
The links seem to work for me. For example, clicking the `3` here goes to the bottom of the page.
<img width="268" alt="image" src="https://github.com/rust-lang/blog.rust-lang.org/assets/43198/fadceaf0-81df-424b-8373-806d4987b8b6">

Can you say which browser and OS you are using? Are the links not underlined? Does clicking them not change the URL fragment to something like `#fn-l`?

**Comment by linkmauve** [comment]
I’m using Firefox nightly on ArchLinux all up to date, and the links aren’t underlined in the footnote itself, not in the link to the footnote, see this screenshot:
![](https://linkmauve.fr/files/rust-footnotes.png)

**Comment by Mark-Simulacrum** [comment]
They probably need to be surrounded in `<` `>` to make them a URL. Footnotes are just text and we don't auto-link in text I guess.

**Comment by ehuss** [comment]
Oh, sorry, I misunderstood. Posted #1303.
