### ISSUE TITLE
Typo in Release Announcement of Rust 1.81?

### ISSUE THREAD

**Issue by ifsheldon** [rust-lang/blog.rust-lang.org#1396]
https://github.com/rust-lang/blog.rust-lang.org/blob/5d68d8caf955f1fb68c23e9d1ee41f37eb773438/posts/2024-09-05-Rust-1.81.0.md?plain=1#L73

Here, based on the context I believe, should be `1.81`?

**Comment by ehuss** [comment]
Looks like this was fixed in #1398.
