### ISSUE TITLE
Blog about the 2017 roadmap?

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/blog.rust-lang.org#143]
[RFC #1728](https://github.com/rust-lang/rfcs/pull/1728) has been merged for the 2017 roadmap, but people who are not "insiders" (not following the Rust subreddit, or matching the rfcs repo, or …) might not know about it. Perhaps a blog post could help make it more visible?

(This is prompted by discussion at https://www.reddit.com/r/rust/comments/5nl3fk/rust_severely_disappoints_me/dccgjzx/ )

**Comment by nikomatsakis** [comment]
Indeed. We've certainly talked about it, not sure that anyone is *doing* it right now. @aturon -- thoughts?

**Comment by aturon** [comment]
Yes, I'm planning to write one up as soon as the tracker is finished (which should happen today).

**Comment by aturon** [comment]
Closed by https://github.com/rust-lang/blog.rust-lang.org/pull/147
