### ISSUE TITLE
Remove unmunged e-mail addresses from old blog posts

### ISSUE THREAD

**Issue by YawarRaza7349** [rust-lang/blog.rust-lang.org#144]
Newer blog posts for releases don't include the e-mail addresses for contributors, so that's good. However, they're still listed alongside the contributor names for the older blog posts. It may help reduce future spam to those e-mail addresses if they were removed from the blog posts on the website. (If not, I'd at least like to remove my own e-mail address.)

I don't mind doing this myself and making a PR, but I thought I'd get some opinions from those who run the blog before doing so.

**Comment by nikomatsakis** [comment]
I think removing all of the e-mail addresses would be fine, personally, particularly if we have stopped doing it on newer releases.

**Comment by YawarRaza7349** [comment]
871c2211201885eae00e7b44788af78d7cd05d01
