### ISSUE TITLE
1.18 Release notes have incorrect windows_subsystem attribute information

### ISSUE THREAD

**Issue by johnthagen** [rust-lang/blog.rust-lang.org#178]
See Rust [forum post](https://users.rust-lang.org/t/solved-console-window-still-opens-when-using-windows-subsystem-windows/11318) for details.

```
#![windows_subsystem(console)]
#![windows_subsystem(windows)]
```

Should be:

```
#![windows_subsystem = "console"]
#![windows_subsystem = "windows"]
```

The form `#![windows_subsystem(console)]` does not actually seem to change anything about the built program.

**Comment by steveklabnik** [comment]
Thanks! I'd love to merge a PR for this, or else I'll get to it soemtime
