### ISSUE TITLE
"Jump straight in" guide (the book?) link doesn't work

### ISSUE THREAD

**Issue by michallepicki** [rust-lang/blog.rust-lang.org#18]
Noticed it on http://blog.rust-lang.org/2015/01/09/Rust-1.0-alpha.html
On the bottom there is a "Jump straight in" link which forwards to http://doc.rust-lang.org/guide.html instead of http://doc.rust-lang.org/book/

**Comment by alexcrichton** [comment]
Oops, thanks!
