### ISSUE TITLE
1.19 library stabilization bullet point missing

### ISSUE THREAD

**Issue by mattico** [rust-lang/blog.rust-lang.org#188]
It seems there's a discrepancy between the GitHub and Jekyll markdown renderers. This last bullet shows up fine in GH, but not on the blog:

![image](https://user-images.githubusercontent.com/853158/28435074-3f875022-6d57-11e7-92a7-8463a20c8bfc.png)

**Comment by steveklabnik** [comment]
This has since been fixed!
