### ISSUE TITLE
License: when creating derivative work, how to credit the original author(s)?

### ISSUE THREAD

**Issue by akavel** [rust-lang/blog.rust-lang.org#256]
I'd like to ~~steal~~ clone the layout/theme of this blog for my own use, and hopefully publishing e.g. on https://themes.gohugo.io/. Given the current [Creative Commons *Attribution* 4.0 license](https://github.com/rust-lang/blog.rust-lang.org/blob/ea2703bb26ba126f3cb85c115c96fd45617f0c8f/LICENSE), my question is: to properly *attribute* the derivative work, *whom* specifically should I attribute the original to?

Something like: "The blog.rust-lang.org authors"? + some (which?) copyright years?

Also, should I put this info e.g. in the layout's footer? or just in the theme's info page & maybe some HTML comments?

I want to be respectful and give credit where credit's due!

*edit:* The CC website seems to have some wiki with general guidelines & examples on [how to attribute derivative works](https://wiki.creativecommons.org/wiki/Best_practices_for_attribution#This_is_a_good_attribution_for_material_from_which_you_created_a_derivative_work), but it's not clear to me how to best apply those in this case...

*edit 2:* Per [CC Best practices for attribution](https://wiki.creativecommons.org/wiki/Best_practices_for_attribution#This_is_a_good_attribution_for_material_from_which_you_created_a_derivative_work), it's good practice to clearly state who's the author, when marking a work with CC-BY license. And in fact, it makes it noticeably  harder for someone (like me) to properly fulfill the "attribution" part, when such explicit declaration is missing...  I searched, but couldn't find such a note either on https://blog.rust-lang.org,  or in the README...

**Comment by Pazzaz** [comment]
I don't think it's an original theme. It looks like they just used the default theme of Jekyll, [minima](https://github.com/jekyll/minima).

**Comment by akavel** [comment]
Uh, OK, that was a surprise to me. But shouldn't the minima's [LICENSE.txt](https://github.com/jekyll/minima/blob/master/LICENSE.txt) be present somewhere in this repo then, to fulfill the original theme's licensing obligations? Or is it already present?

**Comment by steveklabnik** [comment]
We changed away from our old theme entirely, and so this seems moot. Sorry about not getting back to you about this sooner!
