### ISSUE TITLE
Headers should have § links

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/blog.rust-lang.org#280]
The headings in the blog posts have `id`s

https://blog.rust-lang.org/2018/05/10/Rust-1.26.html#nicer-match-bindings

but I can't see any nice way to get that link; I needed to use dev tools to find it.

It would be nice if it had a §-link, like in rustdoc.

**Comment by DJMcNab** [comment]
As of the latest version, they no longer have `id`s. I think this is a regression (the links in the TOC don't work)

**Comment by steveklabnik** [comment]
@DJMcNab that was a temporary regression, they're back now.

I agree this would be a nice feature to have!
