### ISSUE TITLE
Function-like procedural macros in expression position as seen in 1.30 announcement are not stable yet

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/blog.rust-lang.org#285]
Only macros in statement position are stable in 1.30.

```console
error[E0658]: procedural macros cannot be expanded to expressions (see issue #38356)                                           
 --> src/main.rs:5:15                                                                                                          
  |                                                                                                                            
5 |     let sql = sql!(SELECT * FROM posts WHERE id=1);                                                                        
  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The stabilization hasn't landed in nightly yet either.

```console
error[E0658]: procedural macros cannot be expanded to expressions (see issue #54727)                                           
 --> src/main.rs:5:15                                                                                                          
  |                                                                                                                            
5 |     let sql = sql!(SELECT * FROM posts WHERE id=1);                                                                        
  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                         
  |                                                                                                                            
  = help: add #![feature(proc_macro_hygiene)] to the crate attributes to enable
```

Mentioning @steveklabnik.

**Comment by steveklabnik** [comment]
Whoops!

Any ideas on a decent example we could change it to?

**Comment by coder543** [comment]
Will this be stabilized for 1.31? Or is there an issue to track the status of proc macros in expression position?

**Comment by steveklabnik** [comment]
No, it's not clear when this will become stable.

As the error message says, https://github.com/rust-lang/rust/issues/54727 is the tracking issue.

**Comment by dtolnay** [comment]
@steveklabnik the `include_dir!` macro from https://github.com/Michael-F-Bryan/include_dir would make a good example. It is currently implemented using proc-macro-hack and has some crates using it. Could now be written stably as an ordinary procedural macro.

**Comment by sgrif** [comment]
We're going to change the `sql_function!` macro in Diesel to a proc macro since parsing Rust function syntax + looking for special attributes in `macro_rules!` is not fun

**Comment by Ralith** [comment]
> Any ideas on a decent example we could change it to?

Something that compiles a GLSL shader program, perhaps? e.g. vulkano has some really ugly hacks to accomplish this at present.

**Comment by rukai** [comment]
@Ralith Not anymore! :D https://github.com/vulkano-rs/vulkano/pull/1062 
Vulkano now uses the newly stabilised function-like macros, instead of hacking it via `[#derive()]`

**Comment by ubnt-intrepid** [comment]
I'm currently working on introducing a new helper macros in my project, based on `#[proc_macro]` , and found that the expression-style macros could be defined by doing as follows:

```rust
#[proc_macro]
pub fn sql_impl(input: TokenStream) -> TokenStream {
    let expr = derive_sql_expr(input);
    quote::quote!(
        fn output() -> impl sql::Sql {
            #output
        }
    ).into()
}
```

```rust
extern crate sql_impl;
#[doc(hidden)]
pub use sql_impl::*;

#[macro_export(local_inner_macros)]
macro_rules! sql {
    ($($t:tt)*) => {{
        struct __Dummy;
        impl __Dummy {
            sql_impl!($($t)*);
        }
        __Dummy::output()
    }}
}
```

Restrictions:

* The token streams cannot capture any identifiers contained in the caller's scope
    - `let i=0; sql!(SELECT * FROM users WHERE id=i)` should be rejected
* the type of generated expression must be written as a return type (or `impl Trait`)

**Comment by dtolnay** [comment]
Or use https://github.com/dtolnay/proc-macro-hack which lifts both of those restrictions.
