### ISSUE TITLE
Footer links are broken

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/blog.rust-lang.org#304]
The bottom of https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-rust-2018.html contains links to:

- https://blog.rust-lang.org/policies/code-of-conduct
- https://blog.rust-lang.org/policies/licenses
- https://blog.rust-lang.org/policies/media-guide
- https://blog.rust-lang.org/policies/security
- https://blog.rust-lang.org/policies

**Comment by Aloso** [comment]
This has already been fixed AFAIK.
