### ISSUE TITLE
Pull requests against master

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/blog.rust-lang.org#305]
On pull requests against master branch, @rust-highfive leaves a comment saying:

> <img alt="warning" height="20" src="https://camo.githubusercontent.com/2c52f19ba665a24f60c3d3069b05330d86f87046/687474703a2f2f7777772e6a6f73686d617474686577732e6e65742f7761726e696e672e737667"> **Warning** <img alt="warning" height="20" src="https://camo.githubusercontent.com/2c52f19ba665a24f60c3d3069b05330d86f87046/687474703a2f2f7777772e6a6f73686d617474686577732e6e65742f7761726e696e672e737667">
> 
> * Pull requests are usually filed against the gh-pages branch for this repo, but this one is against master. Please double check that you specified the right target!

As far as I can tell, pull requests are intended to be made against master; gh-pages is generated.

**Comment by steveklabnik** [comment]
Yes, thank you! @alexcrichton or @Mark-Simulacrum can we change this, please?

**Comment by Mark-Simulacrum** [comment]
I've updated the highfive configuration but I'm not sure how to deploy it -- maybe @pietroalbini knows?

**Comment by pietroalbini** [comment]
Changes should be deployed now.

**Comment by davidalber** [comment]
@pietroalbini: The deployment does not appear to have fixed this. For example, see [this comment](https://github.com/rust-lang/blog.rust-lang.org/pull/343#issuecomment-447624252).

**Comment by pietroalbini** [comment]
Now it should be fixed. This repository was still pointing to an old instance of highfive instead of the production one.
