### ISSUE TITLE
Bring back the RSS feed

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/blog.rust-lang.org#307]
The RSS feed is gone; I will be bringing it back, but not right this second.

**Comment by shepmaster** [comment]
Thank you @sondr3 and @steveklabnik!

**Comment by mkeedlinger** [comment]
@steveklabnik Sorry to bring this back to life, but I don't see the link for RSS anywhere on the blog's landing page. Is it still available?

**Comment by mkeedlinger** [comment]
Found it from the linked commit: https://blog.rust-lang.org/feed.xml

I've always just gotten feed links from the page I want to see, is having it at `/feed.xml` a standard? Just asking out of ignorance.

**Comment by pietroalbini** [comment]
@mkeedlinger all the blog post pages contain the standard HTML tag to declare the Atom feed:

```
<link rel="alternate" type="application/atom+xml" href="https://blog.rust-lang.org/feed.xml">
```

Most of the clients should pick it up automatically if you try to subscribe to just "blog.rust-lang.org".
