### ISSUE TITLE
Add publish date to blog posts and add it to the front page

### ISSUE THREAD

**Issue by ocamlmycaml** [rust-lang/blog.rust-lang.org#308]
with the increasing number of posts, it'd be good to see when a blog is published in the front page, as well as in the blog post's page. It's hard to tell if an announcement is old or outdated right now.

I'm not sure how this blog works (and I plan on looking into this issue myself later today) and whether we can bring back the dates for existing posts, but at least it'd be good to have it going forward

**Comment by ocamlmycaml** [comment]
Great~!

So i did something. I'm very proud of my design skills /s

**Comment by Aloso** [comment]
I tried it out, it looks like this:

![blog layout](https://user-images.githubusercontent.com/15658558/49669665-5c796a00-fa62-11e8-92b0-c2dd4ba8d36d.png)

A big headline with the year is shown everywhere a new year starts in the list.

This change required a handlebars helper function and a new `bool` field in the `Post` struct. I turned the list into a `<table>`. I'll make a PR.

**Comment by steveklabnik** [comment]
This has now been fixed!
