### ISSUE TITLE
Yellow links in footer: change :hover behaviour

### ISSUE THREAD

**Issue by Aloso** [rust-lang/blog.rust-lang.org#313]
The yellow links in the footer turn blue when hovered. This looks ugly in my opinion.

Also, a change in colour usually stands for an actual change in the data/state. For example, on some websites links turn purple when they are clicked. In forms, fields turn red when invalid input was entered. So, a colour change on :hover might be irritating.

Instead, I suggest to make the links yellow all the time; also, I suggest to remove the **link underlines** and show them only when a link is hovered.

## Advantages

* The links still react to mouse interactions
* The links are better readable without the underline
* Less visual clutter
* The links don't change their colour

## Disadvantages

Since links are usually blue and underlined, this change might make it harder for some to realize that these words are clickable links.

However, today there are many websites with links in different colours. Also, it becomes clear from the context that these words/expressions must be links. I'm assuming that most visitors of this website are clever and experienced enough to figure that out.

**Comment by Aloso** [comment]
I noticed that this style is inherited from the css boilerplate **skeleton.css**, so it might not even be intended.

**Comment by Aloso** [comment]
I'd also suggest to remove the circle bullets (only in the footer). This is what it would look like:

![issue links](https://user-images.githubusercontent.com/15658558/49613163-36db5a80-f9a7-11e8-90d6-d01e23c45a5f.png)

**Comment by steveklabnik** [comment]
This was fixed by https://github.com/rust-lang/blog.rust-lang.org/pull/329
