### ISSUE TITLE
Slightly inconsistent sorting of blog posts

### ISSUE THREAD

**Issue by Aloso** [rust-lang/blog.rust-lang.org#330]
On the homepage, the ordering of the blog posts is not determined for posts released on the same day.

I suggest to include the title into the sorting function, so we get the same order every time the site is built:

```rust
// main.rs, line 119
posts.sort_by_key(|post| format!("{}-{}-{}-{}", post.year, post.month, post.day, post.title));
```

Or, use the url, which is in the format `YYYY/MM/DD/<file name>.html`:

```rust
posts.sort_by_key(|post| post.url.clone());
```

**Comment by steveklabnik** [comment]
Sure, that seems good. Let's just use the URL, since it already has all of the relevant info.
