### ISSUE TITLE
Reduce body width of posts (suggested: 45em)

### ISSUE THREAD

**Issue by nicoburns** [rust-lang/blog.rust-lang.org#347]
The new blog design is very difficult to read compared to the old one. I believe this is due to the new design having a very long line-length (the max-width of the container is 96em, so the line-length is 96 characters).

The recommended line-length is between 45 and 75 characters ([source](https://www.smashingmagazine.com/2014/09/balancing-line-length-font-size-responsive-web-design/)). Personally, I find that changing the body width to 45em greatly increases the readability of posts, so I would recommend changing it to that width.

**Comment by steveklabnik** [comment]
I'd be open to this! Any chance you can make the change and give me some before-after screenshots?

**Comment by nicoburns** [comment]
Before:
<img width="1440" alt="screenshot 2018-12-18 at 23 13 44" src="https://user-images.githubusercontent.com/1007307/50188885-071f4180-031b-11e9-81a2-770b238ff2d7.png">

After:
<img width="1440" alt="screenshot 2018-12-18 at 23 14 13" src="https://user-images.githubusercontent.com/1007307/50188888-0b4b5f00-031b-11e9-84b5-224a247ceed6.png">

Only the "large" breakpoint is affected as the others seem to be more or less fine as is.
