### ISSUE TITLE
`{:class="center"}` on images is no longer rendering

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/blog.rust-lang.org#354]
I happened to land on [this post](https://blog.rust-lang.org/2017/05/15/rust-at-two-years.html) that I happened to have written, unfortunately I don't happen to remember why I added `{:class="center"}` on the image [in the markdown](https://github.com/rust-lang/blog.rust-lang.org/blob/db2a5bc24639f58bdc4a8b9557978e0aeeb3c41f/posts/2017-05-15-rust-at-two-years.md) that isn't being interpreted and currently looks like this:

<img width="900" alt="screen shot 2018-12-21 at 2 22 27 pm" src="https://user-images.githubusercontent.com/193874/50359852-293bde00-052c-11e9-87d0-e51fe45f51d2.png">

I don't remember if that's a markdown feature, a jekyll feature, or a hack.

Is this obsolete and something that should just be removed? Or should the rendering be fixed? Is this feature used anywhere else on the blog? More that I don't know :P

**Comment by steveklabnik** [comment]
I am not sure! We need to investigate though.!

**Comment by steveklabnik** [comment]
I did some digging. apparently it's a feature of `kramdown`: https://about.gitlab.com/2016/07/19/markdown-kramdown-tips-and-tricks/#applying-classes

which the old blog was using: https://github.com/rust-lang/blog.rust-lang.org/blob/14389a87a9f2a119e6588d04090634e057dc8a70/Gemfile.lock#L74

This appears to be non-standard https://stackoverflow.com/questions/1058933/can-i-define-a-class-name-on-paragraph-using-markdown

I think in this specific case, we can remove it, as the class isn't really doing anything, but we should also audit posts to check for any other usages of this.

**Comment by jplatte** [comment]
I've `rg`ed for any remaining uses of this kramdown feature and actually found some! I'll open a PR shortly to remove them, just want to note that I have found cases where this makes a visual difference. If images that aren't wide enough should always be centered, I'm happy to make a PR for that as well.

**Comment by steveklabnik** [comment]
Thanks so much! Yeah, if we can actually center them, that'd be great too.
