### ISSUE TITLE
Link version to announcement

### ISSUE THREAD

**Issue by kellytk** [rust-lang/blog.rust-lang.org#364]
At https://www.rust-lang.org/ "Version 1.32.0" should link to its associated announcement. (https://blog.rust-lang.org/2019/01/17/Rust-1.32.0.html)

**Comment by Mark-Simulacrum** [comment]
This is I believe already tracked on the website repository, and there's also an internals thread seeking community help here: https://internals.rust-lang.org/t/release-blog-post-link-on-website-front-page/9074

**Comment by Mark-Simulacrum** [comment]
This is I believe already tracked on the website repository, and there's also an internals thread seeking community help here: https://internals.rust-lang.org/t/release-blog-post-link-on-website-front-page/9074
