### ISSUE TITLE
Is there any way to e-mail notification of blog posts?

### ISSUE THREAD

**Issue by ianthetechie** [rust-lang/blog.rust-lang.org#371]
Hey all,

Thanks for the great stuff you post here! Is there any way to get notified of new posts? Maybe a mailing list perhaps? I did notice that there's an RSS feed, but I'd prefer email if possible.

**Comment by skade** [comment]
All posts will land in https://this-week-in-rust.org as the topmost post. Would that suffice to you or do you want an immediate email?

**Comment by ianthetechie** [comment]
Ahh, I didn't realize that. I did find TWIR recently. Maybe advertise this a bit more?

**Comment by trevordmiller** [comment]
I agree that an email list would be helpful to stay up-to-date. I do subscribe to TWIR, but it would be nice to have an option to only receive official updates.

**Comment by XAMPPRocky** [comment]
@trevordmiller There is an RSS feed of the blog post, you can link that to any other service to get notifications in the way you want.
