### ISSUE TITLE
Call out RSS feeds for the main and the Inside Rust blogs

### ISSUE THREAD

**Issue by TomasHubelbauer** [rust-lang/blog.rust-lang.org#420]
I can't for the life of me find the RSS feed link on either of the blogs, but I found the main blog feed link in #307 and I figured out the Inside Rust blog using it as well:

- Main Blog: https://blog.rust-lang.org/feed.xml
- Inside Rust Blog: https://blog.rust-lang.org/inside-rust/feed.xml

Would be cool to have links to these guys on the pages itself.

**Comment by rawrmonstar** [comment]
Ha! I came here to make an issue asking for an RSS feed for the two blogs. A link somewhere on the site would definitely be nice IMO.
