### ISSUE TITLE
blog rendering does not include subsection anchors

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/blog.rust-lang.org#49]
I do not know if this is something that can actually be fixed easily, but in my post:

  http://blog.rust-lang.org/2015/04/17/Enums-match-mutation-and-moves.html

i used, in a few places, links to other subsections within the document.

This worked within the github preview of the rendered markdown.  But then the anchors I was referring to disappeared in the redcarpet rendering.

**Comment by pnkfelix** [comment]
I'd include links to the sections where I used such references to subsection anchors, but, ha ha, there are no anchors for the sections.  ;)

**Comment by brson** [comment]
Fixed.
