### ISSUE TITLE
One Year Of Rust post features wrong image.

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/blog.rust-lang.org#578]
The [One year of Rust][p] linked to an image (`http://rustcamp.com/images/after/cupcakes.jpg`)  from an expired domain.

<img width="903" alt="Screenshot 2020-05-04 at 17 10 28" src="https://user-images.githubusercontent.com/4464295/80981560-6f949300-8e2a-11ea-8475-4e41fcd4b4f4.png">

[p]: https://blog.rust-lang.org/2016/05/16/rust-at-one-year.html

**Comment by bjorn3** [comment]
The original: https://web.archive.org/web/20170628094740/http://rustcamp.com/images/after/cupcakes.jpg

**Comment by XAMPPRocky** [comment]
If anyone is interested I would accept a PR that adds that image to the repository and replaces the link.

**Comment by dtolnay** [comment]
It would be good to scrub all the posts of hotlinked images, even if they are not currently broken.

**Comment by XAMPPRocky** [comment]
@dtolnay Good point! I made a seperate issue to track that.
