### ISSUE TITLE
Does "Support BLM" announcement in v1.44 release post mean Black Lives Matter only in this version?

### ISSUE THREAD

**Issue by windoze** [rust-lang/blog.rust-lang.org#611]
Does "Support BLM" announcement in v1.44 release post mean Black Lives Matter only in this version? Otherwise why did you put it in a **release note**?

I think it deserves a better place, such as another post with proper title.

**Comment by BurntSushi** [comment]
Please contact the core team directly via email at core@rust-lang.org for discussion on this topic.
