### ISSUE TITLE
The rust blog should not support "Black Lives Matter"

### ISSUE THREAD

**Issue by porky11** [rust-lang/blog.rust-lang.org#613]
In the [blog post for the new rust release](https://blog.rust-lang.org/2020/06/04/Rust-1.44.0.html) you promote a political position and support the "Black Lives Matter" movement.
I don't like, when organizations promote political views, but since you do, I have to criticize you.
I probably don't have to say that, but I think, it's a good thing not to judge persons based on race.
But there are also a few problems I have with that movement.

# Critics

## Opinionated Information and Race Equality

People of the "Black Lives Matter" prefer to spread news, which support their views. If black people are killed by the police, it's much more important in media than when white people are killed.
It's a problem in both cases and the focus on black people is a step away from "Race Equality".

Also other information are spread opinionated. It's true, that more black people are killed by the police than white people. So you probably cannot call it Fake News.
But you also have to see, that black people are much more violent than white people and do more crimes. This fact is often played down or interpreted to match the views of the "Black Lives Matter" movement by media.
If you think, this rate is mainly because of racist police officers, I'd say, you're a conspiracy theorist. Most people don't care about race nowadays.

Maybe have a look at different sources about this topic to get a more informed view.
[This](https://www.dailywire.com/news/5-statistics-you-need-know-about-cops-killing-aaron-bandler) looks like a good article, but you might find better sources yourself.

Besides, Race shouldn't be relevant nowadays, in my opinion. A movement called "Black Lives Matter" clearly takes a focus on race and might be abused by some political forces, maybe for "black supremecy" or something like that.

Based on these points it might be a good idea to remove the advertisement for that movement.
Maybe you were misinformed yourself.

**Comment by Mark-Simulacrum** [comment]
Please contact the core team directly via email at core@rust-lang.org for discussion on this topic.
