### ISSUE TITLE
ssl certificate for wrong domain name

### ISSUE THREAD

**Issue by genodeftest** [rust-lang/blog.rust-lang.org#62]
https://blog.rust-lang.org/ has a ssl certificate, but it is only valid for www.github.com, not for blog.rust-lang.org.

**Comment by alexcrichton** [comment]
Thanks for the report! This site is hosted with GitHub pages, however, so it's not something that we can fix right now. The tracking issue for moving off GitHub pages as a frontend is here: https://github.com/rust-lang/rust/issues/13180
