### ISSUE TITLE
This repo needs LICENSE/COPYING, also README

### ISSUE THREAD

**Issue by edunham** [rust-lang/blog.rust-lang.org#63]
I assume it's some combination of CC-BY and copyright by respective authors, but we should make that clear. 

Additionally, a README needs to document the purpose of the blog, the contribution process and guidelines (if community contributions are permitted, which is unclear), and the deployment process (GitHub pages).

**Comment by cmr** [comment]
Just came here to leave this and suggest CC-BY :)

**Comment by rjgoldsborough** [comment]
I'm down to markdownify and add this stuff to the repo if anyone would like to write up what should go in where.

**Comment by alexbowers** [comment]
This can now be closed @skade

**Comment by skade** [comment]
@alexbowers I can't close issues on this repos. @edunham can. :)

**Comment by Mark-Simulacrum** [comment]
We have a license now, but we don't yet have a README file. So not quite there yet.

**Comment by marioidival** [comment]
@Mark-Simulacrum @skade yes, we have a README #209

**Comment by marioidival** [comment]
can be closed now?

**Comment by Mark-Simulacrum** [comment]
Yes, thank you!
