### ISSUE TITLE
https://blog.rust-lang.org uses a non-matching certificate for HTTPS

### ISSUE THREAD

**Issue by tanriol** [rust-lang/blog.rust-lang.org#81]
Trying to access https://blog.rust-lang.org causes browsers (Firefox at least) to show a certificate error because it uses a generic github.io certificate, which is not valid for this domain. Manually adding an exception works, but this experience is definitely suboptimal.

**Comment by brson** [comment]
This is a result of hosting on github. To fix this we'd have to deploy to s3.

**Comment by frewsxcv** [comment]
> This is a result of hosting on github. To fix this we'd have to deploy to s3.

These aren't mutually exclusive. It's possible to host on GitHub while using HTTPS. The Servo blog and [my website](https://rwell.org) via CloudFlare.

**Comment by brson** [comment]
We can point the DNS to our (increasingly overburdened and unredundant) nginx https proxy and proxy it to the new github https servers.

**Comment by alexcrichton** [comment]
Done, so this is now fixed
